src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table
 */
class Task
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="Vous devez saisir un titre.")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Vous devez saisir du contenu.")
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDone;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tasks")
     */
    private $user;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_modification;

    public function __construct()
    {
        $this->createdAt = new \Datetime();
        $this->isDone = false;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($content)
    {
        $this->content = $content;
    }

    public function isDone()
    {
        return $this->isDone;
    }

    public function toggle($flag)
    {
        $this->isDone = $flag;
    }

    public function setId(int $id)
    {
        $this->id = $id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getLastModification(): ?\DateTimeInterface
    {
        return $this->last_modification;
    }

    public function setLastModification(?\DateTimeInterface $last_modification): self
    {
        $this->last_modification = $last_modification;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, [
                'label' => 'Titre',
            ])
            ->add('content', TextareaType::class, [
                'label' => 'Description',
            ])
            //->add('author') ===> must be the user authenticated
        ;
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Controller\services\AnonymeUser;
use App\Entity\Task;
use App\Entity\User;
use App\Form\TaskType;
use App\Repository\TaskRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class TaskController extends AbstractController
{
    public function __construct(AnonymeUser $anonymeUser, EntityManagerInterface $entityManager, UserPasswordEncoderInterface $passwordEncoder)
    {
        $anonymeUser->update($entityManager, $passwordEncoder);
    }

    /**
     * @Route("/tasks", name="task_list")
     */
    public function listAction()
    {
        //sleep(5);
        return $this->render('task/list.html.twig', [
            'tasks' => $this->getDoctrine()->getRepository(Task::class)->findBy(['isDone' => 0], ['last_modification' => 'DESC']),
        ]);
    }

    /**
     * @Route("/tasks-is-done", name="task_is_done")
     */
    public function taskListIsDone()
    {
        return $this->render('task/tasksdone.html.twig', [
            'tasks' => $this->getDoctrine()->getRepository('App:Task')->findBy(['isDone' => 1], ['last_modification' => 'DESC']),
        ]);
    }

    /**
     * @Route("/tasks/create", name="task_create")
     */
    public function createAction(Request $request)
    {
        $task = new Task();
        $form = $this->createForm(TaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $user = new User();
            $timezone = new \DateTimeZone('Europe/Paris');
            $time = new \DateTime('now', $timezone);
            $getuser = $this->getDoctrine()->getManager()->getRepository(User::class)->find($this->getUser()->getId());
            $task->setUser($getuser);
            $task->setLastModification($time);
            $em->persist($task);
            $em->flush();

            $this->addFlash('success', 'La tâche a été bien été ajoutée.');

            return $this->redirectToRoute('task_list');
        }

        return $this->render('task/create.html.twig', ['form' => $form->createView()]);
    }

    /**
     * @Route("/tasks/{id}/edit", name="task_edit")
     */
    public function editAction(Request $request, $id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $task = $entityManager->getRepository(Task::class)->find($id);

        if (!$task) {
            throw $this->createNotFoundException('Aucun produit trouvé pour l\id : '.$id);
        }

        $form = $this->createForm(TaskType::class, $task);
        $timezone = new \DateTimeZone('Europe/Paris');
        $time = new \DateTime('now', $timezone);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //$getuser = $this->getDoctrine()->getManager()->getRepository(User::class)->find($this->getUser()->getId());
            //$task->setUser($getuser);
            $task->setLastModification($time);
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'La tâche a bien été modifiée.');

            return $this->redirectToRoute('task_list');
        }

        return $this->render('task/edit.html.twig', [
            'form' => $form->createView(),
            'task' => $task,
        ]);
    }

    /**
     * @Route("/tasks/{id}/toggle", name="task_toggle")
     */
    public function toggleTaskAction(TaskRepository $taskRepository, $id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $task = $entityManager->getRepository(Task::class)->find($id);

        if (!$task) {
            throw $this->createNotFoundException('Aucun produit trouvé pour l\id : '.$id);
        }

        $task->isDone() ? $task->toggle(0) : $task->toggle(1);
        $entityManager->flush();

        $this->addFlash('success', sprintf('La tâche %s a bien été marquée comme faite.', $task->getTitle()));

        return $this->redirectToRoute('task_list');
    }

    /**
     * @Route("/tasks/{id}/delete", name="task_delete")
     *
     * @param Task $task
     */
    public function deleteTaskAction($id, TaskRepository $taskRepository): Response
    {
        $task = $taskRepository->find($id);
        $em = $this->getDoctrine()->getManager();
        $em->remove($task);
        $em->flush();

        $this->addFlash('success', 'La tâche a bien été supprimée.');

        return $this->redirectToRoute('task_list');
    }
}

templates/task/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="row">
        {{ form_start(form, {'action' : path('task_create')}) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-success pull-right">Ajouter</button>
        {{ form_end(form) }}

        <a href="{{ path('task_list') }}" class="btn btn-primary">Retour à la liste des tâches</a>
    </div>
{% endblock %}

templates/task/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="row">
        {{ form_start(form, {'action' : path('task_edit', { 'id' : task.id })}) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-success pull-right">Modifier</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/task/list.html.twig
{% extends 'base.html.twig' %}

{% block header_img %}<img class="slide-image" src="{{ asset('img/todolist_content.jpg') }}"
                           alt="todo list">{% endblock %}

{% block body %}
    <div style="width: 100%;">
        <a href="{{ path('task_create') }}" class="btn btn-info pull-right">Créer une tâche</a>
    </div>
    <br><br>
    <div class="row">
        {% for task in tasks %}
            <div class="col-sm-4 col-lg-4 col-md-4">
                <div style="margin:20px 5px 20px 5px;" class="thumbnail">
                    <div style="height: 180px;" class="caption">
                        <h4 class="pull-right">
                            {% if task.isDone %}<span class="glyphicon glyphicon-ok"></span>{% else %}<span
                                    class="glyphicon glyphicon-remove"></span>{% endif %}
                        </h4>
                        <h4><a href="{{ path('task_edit', {'id' : task.id }) }}">{{ task.title }}</a></h4>
                        <p>{{ task.content | slice(0, 150) }}</p><br>
                        {% if task.user.id  %}
                            {% if task.lastModification %}
                                <span>Dernière modification le {{ task.lastModification | date("d/m/Y à H:i:s") }}</span><br>
                                <span>Créée par {{ task.user.username }}</span>
                            {% endif %}
                        {% endif %}
                    </div>
                    <div>
                        <form action="{{ path('task_toggle', {'id' : task.id }) }}">
                            <button style="margin-right: 10px!important;margin-top:10px;" class="btn btn-success btn-sm pull-right">
                                {% if not task.isDone %}Marquer comme faite{% else %}Marquer non terminée{% endif %}
                            </button>
                        </form>
                        {% if (app.user.id is same as task.user.id) or (task.user.roles.0 is same as "ROLE_ANONYME" and app.user.roles.0 is same as "ROLE_ADMIN") %}
                        <form action="{{ path('task_delete', {'id' : task.id }) }}">
                            <button style="margin-right: 10px!important;margin-top:10px;" class="btn btn-danger btn-sm pull-right">Supprimer</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% else %}
            <div class="alert alert-warning" role="alert">
                Il n'y a pas encore de tâche enregistrée.
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/task/tasksdone.html.twig
{% extends 'base.html.twig' %}

{% block header_img %}<img class="slide-image" src="{{ asset('img/todolist_content.jpg') }}"
                           alt="todo list">{% endblock %}

{% block body %}
    <div style="width: 100%;">
        <a href="{{ path('task_create') }}" class="btn btn-info pull-right">Créer une tâche</a>
    </div>
    <br><br>
    <div class="row">
        {% for task in tasks %}
            <div class="col-sm-4 col-lg-4 col-md-4">
                <div style="margin:20px 5px 20px 5px;" class="thumbnail">
                    <div style="height: 180px;" class="caption">
                        <h4 class="pull-right">
                            {% if task.isDone %}<span class="glyphicon glyphicon-ok"></span>{% else %}<span
                                    class="glyphicon glyphicon-remove"></span>{% endif %}
                        </h4>
                        <h4><a href="{{ path('task_edit', {'id' : task.id }) }}">{{ task.title }}</a></h4>
                        <p>{{ task.content | slice(0, 150) }}</p><br>
                        {% if task.user  %}
                            {% if task.lastModification %}
                                <span>Dernière modification le {{ task.lastModification | date("d/m/Y à H:i:s") }}</span><br>
                                <span>Créée par {{ task.user.username }}</span>
                            {% endif %}
                        {% endif %}
                    </div>
                    <div>
                        <form action="{{ path('task_toggle', {'id' : task.id }) }}">
                            <button style="margin-right: 10px!important;margin-top:10px;" class="btn btn-success btn-sm pull-right">
                                {% if not task.isDone %}Marquer comme faite{% else %}Marquer non terminée{% endif %}
                            </button>
                        </form>
                        {% if (app.user.id is same as task.user.id) or (task.user.roles.0 is same as "ROLE_ANONYME" and app.user.roles.0 is same as "ROLE_ADMIN") %}
                            <form action="{{ path('task_delete', {'id' : task.id }) }}">
                                <button style="margin-right: 10px!important;margin-top:10px;" class="btn btn-danger btn-sm pull-right">Supprimer</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% else %}
            <div class="alert alert-warning" role="alert">
                Il n'y a pas encore de tâche enregistrée.
            </div>
        {% endfor %}
    </div>
{% endblock %}